volumes:
    postgre_volume:

networks:
    default_network:
        driver: bridge

services:
    backend:
        depends_on:
            - rabbitmq
            - postgre
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        networks:
            - default_network
        environment:
            ASPNETCORE_ENVIRONMENT: Development
    rabbitmq:
        image: rabbitmq:4.0.2-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - default_network
    postgre:
        image: postgres:17.0
        ports:
            - 5432:5432
        volumes:
            - postgre_volume:/var/lib/postgresql/data
        networks:
            - default_network
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
    pgadmin:
        image: dpage/pgadmin4:8.12.0
        depends_on:
            - postgre
        ports:
            - 5050:80
        networks:
            - default_network
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root